projects:
  knockout:
    schema: "script/__generated__/knockout.graphql"
    documents:
      - 'src/services/knockout/**/*.ts'
      - 'script/__generated__/knockout.graphql'
    extensions:
      endpoints:
        default:
          url: ${GQLGEN_SCHEMA}
          headers:
            Authorization: bearer ${GQLGEN_TOKEN}
            X-Tenant-ID: ${GQLGEN_TENANT_ID}
