kind: Service
apiVersion: v1
metadata:
  name: adminx-ui
  namespace: dev-v2
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30777
  selector:
    app: adminx-ui
  type: NodePort
