kind: Deployment
apiVersion: apps/v1
metadata:
  name: adminx-ui
  namespace: dev-v2
  labels:
    app: adminx-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminx-ui
  template:
    metadata:
      labels:
        app: adminx-ui
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: adminx-nginx-config
            defaultMode: 420
      containers:
        - name: adminx-ui
          image: registry.hycapital.hk/woocoos/adminx-ui:v0.0.1.e43a36f
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 100Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: adminx-ui
  namespace: dev-v2
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30777
  selector:
    app: adminx-ui
  type: NodePort
